"""
Smart Education - Personalized Learning Resource Recommendations
================================================================
GUI module rendering personalized remedial recommendations generated by
Model 4 (Autoencoder + Knowledge Graph Recommender) based on diagnosed
student knowledge state deficits and concept dependency graphs.
"""

import math
from typing import Dict, List, Any, Optional, Set

import numpy as np
import pandas as pd
import plotly.express as px
import plotly.graph_objects as go
import streamlit as st

from services.inference_service import (
    get_model_results,
    get_plot_path,
    predict_student,
)


def _format_duration(duration_sec: Any) -> str:
    """Safely formats lecture duration in seconds to a human-readable string."""
    try:
        val = int(duration_sec)
        if val <= 0:
            return "Standard"
        mins = val // 60
        secs = val % 60
        if mins > 0:
            return f"{val}s ({mins}m {secs}s)"
        return f"{val}s"
    except (ValueError, TypeError):
        return "-"


def _build_recommendations_dataframe(recommendations: List[Dict[str, Any]]) -> pd.DataFrame:
    """
    Transforms the raw engine recommendations list into a clean, formatted DataFrame.
    Fields handled: type, id, concept, part, duration_sec, linked_question, bundle_id.
    """
    rows = []
    for idx, item in enumerate(recommendations, start=1):
        raw_type = str(item.get("type", "unknown")).lower()
        res_id = str(item.get("id", "N/A"))
        concept_val = item.get("concept", "N/A")
        concept_str = f"Concept #{concept_val}" if concept_val != "N/A" else "N/A"

        part_val = item.get("part")
        part_str = f"Part {part_val}" if part_val is not None and str(part_val).strip() not in ("", "None", "nan") else "-"

        # Duration for lectures
        dur_val = item.get("duration_sec")
        dur_str = _format_duration(dur_val) if raw_type == "lecture" else "-"

        # Linked question for explanations
        lq_val = item.get("linked_question")
        lq_str = str(lq_val) if (raw_type == "explanation" and lq_val and str(lq_val) not in ("None", "nan")) else "-"

        # Bundle ID for practice questions
        bundle_val = item.get("bundle_id")
        bundle_str = str(bundle_val) if (raw_type == "question" and bundle_val and str(bundle_val) not in ("None", "nan", "")) else "-"

        # Educational pedagogy description
        if raw_type == "lecture":
            role_str = "Foundational Video Lecture (Conceptual Remediation)"
            display_type = "Lecture"
        elif raw_type == "explanation":
            role_str = "Step-by-Step Solution (Error Analysis & Worked Example)"
            display_type = "Explanation"
        elif raw_type == "question":
            role_str = "Targeted Practice Question (Active Recall & Reinforcement)"
            display_type = "Question"
        else:
            role_str = "Adaptive Learning Asset"
            display_type = raw_type.capitalize()

        rows.append({
            "Rank": idx,
            "Type": display_type,
            "Resource ID": res_id,
            "Concept": concept_str,
            "Concept ID": concept_val,
            "Part": part_str,
            "Duration": dur_str,
            "Linked Question": lq_str,
            "Bundle ID": bundle_str,
            "Pedagogical Role": role_str,
        })

    return pd.DataFrame(rows)


def _build_learning_gaps_dataframe(learning_gaps: List[Dict[str, Any]]) -> pd.DataFrame:
    """Transforms diagnosed concept deficits into a structured DataFrame."""
    rows = []
    for idx, gap in enumerate(learning_gaps, start=1):
        cid = gap.get("concept_id", gap.get("concept", "N/A"))
        cname = gap.get("concept_name", f"Concept #{cid}")
        mastery = float(gap.get("mastery", gap.get("mastery_score", 0.0)))
        attempts = int(gap.get("attempts", gap.get("total_attempts", 0)))
        recent_acc = float(gap.get("recent_accuracy", mastery))
        severity = float(gap.get("gap_severity", max(0.0, 0.60 - mastery)))

        rows.append({
            "Priority": idx,
            "Concept ID": cid,
            "Concept Name": cname,
            "Mastery Score": round(mastery, 4),
            "Mastery Rate": f"{mastery * 100:.1f}%",
            "Attempts": attempts,
            "Recent Accuracy": f"{recent_acc * 100:.1f}%",
            "Deficit vs 60% Target": f"{severity * 100:.1f}%",
            "Severity Level": "Critical Deficit (<40%)" if mastery < 0.40 else "Needs Reinforcement (<60%)",
        })

    return pd.DataFrame(rows)


def _build_concept_subgraph_figure(
    gap_concept_ids: List[int],
    concept_graph: Dict[int, Set[int]],
    max_neighbors_per_node: int = 5,
) -> Optional[go.Figure]:
    """
    Renders an interactive 2D node-link network visualization of the student's
    weak concepts and their direct co-occurrence neighbors in the curriculum.
    """
    if not concept_graph or not gap_concept_ids:
        return None

    # Collect nodes (primary gap nodes + limited neighbors)
    primary_nodes = set(gap_concept_ids[:5])  # focus on top 5 gaps
    neighbor_nodes = set()
    edges = []

    for p in primary_nodes:
        nbrs = sorted(list(concept_graph.get(p, set())))[:max_neighbors_per_node]
        for n in nbrs:
            neighbor_nodes.add(n)
            edges.append((p, n))

    all_nodes = list(primary_nodes.union(neighbor_nodes))
    if not all_nodes:
        return None

    # Deterministic circular layout centered around primary nodes
    node_positions = {}
    n_total = len(all_nodes)
    for i, node in enumerate(all_nodes):
        angle = 2 * math.pi * i / n_total
        radius = 0.55 if node in primary_nodes else 1.0
        node_positions[node] = (radius * math.cos(angle), radius * math.sin(angle))

    # Edge traces
    edge_x = []
    edge_y = []
    for u, v in edges:
        if u in node_positions and v in node_positions:
            edge_x.extend([node_positions[u][0], node_positions[v][0], None])
            edge_y.extend([node_positions[u][1], node_positions[v][1], None])

    fig = go.Figure()

    fig.add_trace(go.Scatter(
        x=edge_x,
        y=edge_y,
        mode="lines",
        line=dict(width=1.5, color="#CBD5E1"),
        hoverinfo="none",
        showlegend=False,
    ))

    # Primary gap nodes (red)
    prim_x = [node_positions[n][0] for n in primary_nodes if n in node_positions]
    prim_y = [node_positions[n][1] for n in primary_nodes if n in node_positions]
    prim_text = [f"Weak Concept #{n}" for n in primary_nodes if n in node_positions]
    prim_hover = [
        f"<b>Concept #{n}</b><br>Role: Diagnosed Learning Gap<br>Neighbors: {len(concept_graph.get(n, set()))}"
        for n in primary_nodes if n in node_positions
    ]

    fig.add_trace(go.Scatter(
        x=prim_x,
        y=prim_y,
        mode="markers+text",
        text=prim_text,
        textposition="top center",
        marker=dict(size=18, color="#EF4444", line=dict(color="#991B1B", width=2)),
        hoverinfo="text",
        hovertext=prim_hover,
        name="Diagnosed Weak Concept",
    ))

    # Neighbor co-occurring nodes (blue)
    nbr_only = [n for n in neighbor_nodes if n not in primary_nodes and n in node_positions]
    if nbr_only:
        nbr_x = [node_positions[n][0] for n in nbr_only]
        nbr_y = [node_positions[n][1] for n in nbr_only]
        nbr_text = [f"#{n}" for n in nbr_only]
        nbr_hover = [
            f"<b>Concept #{n}</b><br>Role: Co-occurring Prerequisite<br>Co-occurs with Weak Concepts"
            for n in nbr_only
        ]

        fig.add_trace(go.Scatter(
            x=nbr_x,
            y=nbr_y,
            mode="markers+text",
            text=nbr_text,
            textposition="bottom center",
            marker=dict(size=13, color="#3B82F6", line=dict(color="#1D4ED8", width=1.5)),
            hoverinfo="text",
            hovertext=nbr_hover,
            name="Co-occurring / Prerequisite Concept",
        ))

    fig.update_layout(
        title="Curriculum Co-Occurrence Neighborhood for Diagnosed Gaps",
        showlegend=True,
        legend=dict(orientation="h", yanchor="bottom", y=1.02, xanchor="right", x=1),
        xaxis=dict(showgrid=False, zeroline=False, showticklabels=False),
        yaxis=dict(showgrid=False, zeroline=False, showticklabels=False),
        margin=dict(l=20, r=20, t=50, b=20),
        height=380,
        plot_bgcolor="#F8FAFC",
        paper_bgcolor="#FFFFFF",
    )
    return fig


def render(engine=None):
    """
    Main entry point for the Personalized Recommendations page.
    Renders the recommendation suite from st.session_state['last_prediction']
    along with Model 4 benchmark metrics and Concept Dependency Graph architecture.
    """
    st.title("Personalized Recommendations")
    st.caption(
        "Adaptive intervention engine mapping diagnosed learner deficits to authentic "
        "EdNet curriculum assets (lectures, explanations, and practice questions)."
    )

    # ------------------------------------------------------------------
    # 1. Retrieve Current Prediction from Session State
    # ------------------------------------------------------------------
    result = st.session_state.get("last_prediction")

    if not result:
        st.info("Run a prediction in Student Analysis first.")

        # Quick convenience launcher for benchmark student if engine is online
        if engine is not None:
            st.markdown("#### Quick Evaluation Launcher")
            st.caption(
                "Alternatively, generate an instant diagnostic and recommendation set "
                "for authentic benchmark student **u1165** directly:"
            )
            col_launch, _ = st.columns([1.5, 3])
            with col_launch:
                if st.button("Run Quick Demo (Student u1165)", type="primary", use_container_width=True):
                    with st.spinner("Executing multi-model inference for u1165..."):
                        demo_result = predict_student(engine, "u1165")
                        if demo_result:
                            st.session_state["last_prediction"] = demo_result
                            st.rerun()

        st.divider()

        # Render global recommender architecture & offline metrics even if no student is active
        _render_model4_metrics_and_graph(engine, gap_concept_ids=[])
        return

    # ------------------------------------------------------------------
    # 2. Prediction Exists: Student Header
    # ------------------------------------------------------------------
    student_id = result.get("student_id", "Simulated Learner")
    split_info = result.get("split", "Evaluation").upper()
    total_events = result.get("total_events", 0)
    inference_time = result.get("inference_time_ms", 0.0)

    # Extract ensemble probability if available
    predictions = result.get("predictions", {})
    consensus_prob = predictions.get("Ensemble Consensus")

    with st.container():
        st.markdown(
            f"""
            <div style="background-color: #F1F5F9; border-left: 5px solid #2563EB; padding: 12px 18px; border-radius: 6px; margin-bottom: 1.2rem;">
                <div style="display: flex; justify-content: space-between; align-items: center; flex-wrap: wrap;">
                    <div>
                        <span style="font-size: 1.15rem; font-weight: 700; color: #1E293B;">
                            Learner Profile: <code style="color: #2563EB; font-size: 1.2rem;">{student_id}</code>
                        </span>
                        <span style="margin-left: 12px; background: #DBEAFE; color: #1E40AF; padding: 2px 8px; border-radius: 12px; font-size: 0.8rem; font-weight: 600;">
                            {split_info} SET
                        </span>
                    </div>
                    <div style="color: #64748B; font-size: 0.88rem; margin-top: 4px;">
                        Historical Events: <b>{total_events:,}</b> | Latency: <b>{inference_time:.1f} ms</b>
                    </div>
                </div>
            </div>
            """,
            unsafe_allow_html=True,
        )

    # ------------------------------------------------------------------
    # 3. Top Recommendations Table & Breakdown Pie Chart
    # ------------------------------------------------------------------
    st.markdown("### Top Recommended Learning Resources")
    st.caption(
        "Interventions ranked according to pedagogical hierarchy: "
        "Lectures (Conceptual Theory) -> Explanations (Worked Examples) -> Questions (Active Practice)."
    )

    raw_recs = result.get("recommendations", [])

    if not raw_recs:
        st.warning(
            "No recommendations generated for this student. "
            "All evaluated concepts are above the 60% mastery threshold or no unattempted candidate items were found."
        )
    else:
        df_recs = _build_recommendations_dataframe(raw_recs)

        # Layout: 2 Columns (Table left, Pie Chart right)
        col_table, col_chart = st.columns([1.8, 1.2])

        with col_table:
            # Display formatted table
            display_cols = [
                "Rank",
                "Type",
                "Resource ID",
                "Concept",
                "Part",
                "Duration",
                "Linked Question",
                "Bundle ID",
            ]
            st.dataframe(
                df_recs[display_cols],
                use_container_width=True,
                hide_index=True,
            )

            # Optional CSV download
            csv_data = df_recs.to_csv(index=False).encode("utf-8")
            st.download_button(
                label="Download Remedial Plan (CSV)",
                data=csv_data,
                file_name=f"recommendations_{student_id}.csv",
                mime="text/csv",
            )

        with col_chart:
            # Resource Type Breakdown Pie Chart
            type_counts = df_recs["Type"].value_counts().reset_index()
            type_counts.columns = ["Resource Type", "Count"]

            color_map = {
                "Lecture": "#3B82F6",       # Blue
                "Explanation": "#10B981",   # Emerald
                "Question": "#F59E0B",      # Amber
            }

            fig_pie = px.pie(
                type_counts,
                names="Resource Type",
                values="Count",
                title="Resource Type Distribution",
                color="Resource Type",
                color_discrete_map=color_map,
                hole=0.45,
            )
            fig_pie.update_traces(
                textposition="inside",
                textinfo="percent+label",
                marker=dict(line=dict(color="#FFFFFF", width=2)),
            )
            fig_pie.update_layout(
                margin=dict(l=10, r=10, t=40, b=10),
                height=260,
                showlegend=True,
                legend=dict(orientation="h", yanchor="bottom", y=-0.2, xanchor="center", x=0.5),
            )
            st.plotly_chart(fig_pie, use_container_width=True)

        # Pedagogical notes expander
        with st.expander("View Resource Details & Pedagogical Intent"):
            for _, r in df_recs.iterrows():
                st.markdown(
                    f"- **#{r['Rank']} [{r['Type']}] `{r['Resource ID']}`** targeting **{r['Concept']}** ({r['Part']}): "
                    f"{r['Pedagogical Role']} "
                    f"*(Duration: {r['Duration']} | Linked Q: {r['Linked Question']} | Bundle: {r['Bundle ID']})*"
                )

        # Real-Time Video Attention Modulation (Optional Non-Breaking Adapter)
        with st.expander("🎥 Real-Time Attention Signal Context (Optional Modulation)", expanded=False):
            st.caption("Apply real-time visual & acoustic attention telemetry to dynamically adapt intervention pacing.")
            att_context = st.radio(
                "Active / Simulated Attention State",
                ["Use Active Video Session", "Simulate Inattentive", "Simulate Partially Attentive", "Simulate Attentive"],
                horizontal=True,
                key="rec_att_choice"
            )

            last_att = st.session_state.get("last_attention_result", {}).get("attention", {})
            if att_context == "Use Active Video Session" and last_att.get("attention_class"):
                sel_class = last_att.get("attention_class")
                sel_conf = last_att.get("confidence", 0.5)
                st.write(f"Active Video Telemetry Attention: **{sel_class}** ({sel_conf*100:.1f}% confidence)")
            elif "Inattentive" in att_context:
                sel_class = "Inattentive"
                sel_conf = 0.85
            elif "Partially" in att_context:
                sel_class = "Partially Attentive"
                sel_conf = 0.75
            else:
                sel_class = "Attentive"
                sel_conf = 0.90

            try:
                from attention.attention_pipeline import adjust_recommendations_by_attention
                modulation = adjust_recommendations_by_attention(raw_recs, sel_class, sel_conf)
                st.info(f"**Strategy**: {modulation['strategy_title']}\n\n{modulation['rationale']}")

                st.markdown("**Adapted Recommendation Sequencing:**")
                for idx, r in enumerate(modulation["adapted_recommendations"][:5], 1):
                    pacing = f" • *{r.get('pacing_tag')}*" if "pacing_tag" in r else ""
                    dur = f" ({r.get('duration_sec')}s)" if r.get("duration_sec") else ""
                    st.markdown(f"{idx}. **[{r.get('type').upper()}]** `{r.get('id')}` — Targets Concept #{r.get('concept')}{dur}{pacing}")
            except Exception as e:
                st.caption(f"Attention modulation preview unavailable: {e}")

        # ── AI Pedagogical Insights & Study Plan (Ollama Integration) ──
        with st.expander("🤖 AI Pedagogical Insights & Why These Resources?", expanded=False):
            st.caption("Local Generative AI layer (Ollama) interprets the neural recommender's selections and provides actionable study plans.")
            col_ai1, col_ai2 = st.columns(2)
            with col_ai1:
                if st.button("💡 Explain Why These Resources?", key="btn_explain_recs"):
                    with st.spinner("Generating pedagogical explanation with Ollama..."):
                        from ollama_ai.learner_context import build_learner_context
                        from ollama_ai.response_generator import ResponseGenerator
                        ai_ctx = build_learner_context(inference_result=result, student_id=student_id)
                        if 'sel_class' in locals():
                            ai_ctx.attention_state = sel_class
                            ai_ctx.attention_confidence = sel_conf
                        ai_gen = ResponseGenerator()
                        st.session_state["rec_ai_explanation"] = ai_gen.explain_recommendations(ai_ctx)

            with col_ai2:
                target_hrs = st.slider("Target Study Duration (Hours)", min_value=0.5, max_value=4.0, value=2.0, step=0.5, key="rec_ai_hours")
                if st.button("📅 Generate Personalized Study Plan", key="btn_study_plan"):
                    with st.spinner("Constructing study schedule with Ollama..."):
                        from ollama_ai.learner_context import build_learner_context
                        from ollama_ai.response_generator import ResponseGenerator
                        ai_ctx = build_learner_context(inference_result=result, student_id=student_id)
                        if 'sel_class' in locals():
                            ai_ctx.attention_state = sel_class
                            ai_ctx.attention_confidence = sel_conf
                        ai_gen = ResponseGenerator()
                        st.session_state["rec_ai_plan"] = ai_gen.generate_study_plan(ai_ctx, target_hours=target_hrs)

            if "rec_ai_explanation" in st.session_state:
                exp_data = st.session_state["rec_ai_explanation"]
                badge = "🟢 Ollama AI" if exp_data.get("ai_available") else "⚪ Deterministic Pedagogical Fallback (Ollama Offline)"
                st.markdown(f"**Source:** `{badge}`")
                st.markdown(exp_data.get("explanation", ""))

            if "rec_ai_plan" in st.session_state:
                plan_data = st.session_state["rec_ai_plan"]
                badge = "🟢 Ollama AI" if plan_data.get("ai_available") else "⚪ Deterministic Pedagogical Fallback (Ollama Offline)"
                st.markdown(f"**Source:** `{badge}`")
                st.markdown(plan_data.get("explanation", ""))

    st.divider()


    # ------------------------------------------------------------------
    # 4. Learning Gaps that Triggered Recommendations
    # ------------------------------------------------------------------
    st.markdown("### Diagnosed Learning Deficiencies")
    st.caption("Concepts flagged with estimated mastery score below the 60.0% remediation threshold.")

    raw_gaps = result.get("learning_gaps", [])

    if not raw_gaps:
        st.success(
            "No critical concept deficiencies detected! Student is performing well above the 60% mastery threshold."
        )
    else:
        df_gaps = _build_learning_gaps_dataframe(raw_gaps)

        col_gap_metrics, col_gap_chart = st.columns([1.1, 1.9])

        with col_gap_metrics:
            st.metric(
                label="Total Deficit Concepts",
                value=len(df_gaps),
                delta=f"Rank 1: Concept #{df_gaps.iloc[0]['Concept ID']}" if not df_gaps.empty else None,
                delta_color="inverse",
            )
            critical_count = int((df_gaps["Mastery Score"] < 0.40).sum())
            st.metric(
                label="Critical Gaps (<40% Mastery)",
                value=critical_count,
                help="High priority concepts requiring immediate video lecture remediation",
            )
            avg_mastery = df_gaps["Mastery Score"].mean()
            st.metric(
                label="Average Deficit Mastery",
                value=f"{avg_mastery * 100:.1f}%",
                help="Mean mastery across all identified weak concepts",
            )

        with col_gap_chart:
            # Bar chart of top deficit concepts
            plot_df = df_gaps.head(8).copy()
            fig_gap_bar = px.bar(
                plot_df,
                x="Concept ID",
                y="Mastery Score",
                title="Top Weak Concepts vs 60% Mastery Target",
                labels={"Concept ID": "Concept Tag", "Mastery Score": "Mastery Probability"},
                color="Mastery Score",
                color_continuous_scale="Reds_r",
                range_y=[0, 1.0],
                text="Mastery Rate",
            )
            fig_gap_bar.add_hline(
                y=0.60,
                line_dash="dash",
                line_color="#EF4444",
                annotation_text="60% Remediation Cutoff",
                annotation_position="top right",
            )
            fig_gap_bar.update_traces(textposition="outside")
            fig_gap_bar.update_layout(
                margin=dict(l=20, r=20, t=40, b=20),
                height=260,
                coloraxis_showscale=False,
            )
            st.plotly_chart(fig_gap_bar, use_container_width=True)

        # Full table of learning gaps
        with st.expander(f"Inspect All {len(df_gaps)} Diagnosed Deficiencies", expanded=False):
            st.dataframe(
                df_gaps[
                    [
                        "Priority",
                        "Concept ID",
                        "Concept Name",
                        "Mastery Rate",
                        "Attempts",
                        "Recent Accuracy",
                        "Deficit vs 60% Target",
                        "Severity Level",
                    ]
                ],
                use_container_width=True,
                hide_index=True,
            )

    st.divider()

    # ------------------------------------------------------------------
    # 5. Recommendation Engine Info & Concept Dependency Graph
    # ------------------------------------------------------------------
    gap_ids = [int(g.get("concept_id", g.get("concept", 0))) for g in raw_gaps]
    _render_model4_metrics_and_graph(engine, gap_concept_ids=gap_ids)


def _render_model4_metrics_and_graph(engine, gap_concept_ids: List[int]):
    """
    Renders the recommendation engine evaluation metrics (from model4_results.json)
    and the Concept Dependency Graph architecture section.
    """
    # ------------------------------------------------------------------
    # Section A: Model 4 Offline Evaluation Metrics
    # ------------------------------------------------------------------
    st.markdown("### Recommendation Engine Benchmark (Model 4)")
    st.caption(
        "Evaluation metrics computed on authentic held-out test cohort for the "
        "Autoencoder + Recommendation Network."
    )

    m4_data = get_model_results(4)
    if not m4_data:
        st.warning("Model 4 benchmark results (`model4_results.json`) not found in reports directory.")
    else:
        test_metrics = m4_data.get("test_metrics", {})

        # Extract hit rates, reconstruction MSE, and NDCG
        hr5 = test_metrics.get("HitRate@5", test_metrics.get("hit_rate_at_5"))
        hr10 = test_metrics.get("HitRate@10", test_metrics.get("hit_rate_at_10"))
        recon_mse = test_metrics.get("reconstruction_mse")
        ndcg10 = test_metrics.get("NDCG@10")
        prec5 = test_metrics.get("Precision@5")
        recall5 = test_metrics.get("Recall@5")
        cv_mse = m4_data.get("cv_reconstruction_mse", {})
        cv_mean = cv_mse.get("mean")

        # KPI Metrics Cards
        col1, col2, col3, col4 = st.columns(4)

        with col1:
            val_str = f"{hr5 * 100:.2f}%" if hr5 is not None else "N/A"
            st.metric(
                label="Hit Rate @ 5",
                value=val_str,
                delta="Top-5 Catalog Match",
                help="Proportion of students for whom at least one recommended item matched authentic subsequent interactions.",
            )

        with col2:
            val_str = f"{hr10 * 100:.2f}%" if hr10 is not None else "N/A"
            st.metric(
                label="Hit Rate @ 10",
                value=val_str,
                delta="Top-10 Catalog Match",
                help="Proportion of students for whom at least one recommended item matched authentic subsequent interactions within 10 picks.",
            )

        with col3:
            val_str = f"{recon_mse:.4f}" if recon_mse is not None else "N/A"
            delta_str = f"vs CV: {cv_mean:.4f}" if cv_mean is not None else None
            st.metric(
                label="Reconstruction MSE",
                value=val_str,
                delta=delta_str,
                delta_color="inverse",
                help="Mean Squared Error of the Autoencoder latent space reconstructing student multi-concept feature states.",
            )

        with col4:
            val_str = f"{ndcg10:.4f}" if ndcg10 is not None else "N/A"
            st.metric(
                label="NDCG @ 10",
                value=val_str,
                delta="Ranking Quality",
                help="Normalized Discounted Cumulative Gain penalizing relevant materials ranked lower in candidate list.",
            )

        # Extended metrics in expander
        with st.expander("Detailed Recommendation Engine Parameters & Metrics"):
            m_col1, m_col2, m_col3, m_col4 = st.columns(4)
            m_col1.metric("Precision @ 5", f"{prec5 * 100:.2f}%" if prec5 is not None else "N/A")
            m_col2.metric("Recall @ 5", f"{recall5 * 100:.2f}%" if recall5 is not None else "N/A")
            m_col3.metric("Parameters", f"{m4_data.get('parameters', 103368):,}")
            m_col4.metric("Diagnosis", m4_data.get("diagnosis", "Healthy Fit"))

            st.markdown(
                """
                **Evaluation Protocol**:
                - **HitRate@K**: Measures recommendation relevance by evaluating whether recommended resources appeared in the student's authentic subsequent interaction session.
                - **Autoencoder Latent Representation**: Compresses 10-dimensional dynamic performance features into an 8-dimensional bottleneck to eliminate noise before scoring.
                - **Candidate Filtering**: Automatically excludes questions and lectures previously completed by the learner to guarantee non-redundancy.
                """
            )

            # Training Curves Plot
            plot_path = get_plot_path("model4_corrected_curves.png")
            if plot_path:
                st.image(
                    str(plot_path),
                    caption="Model 4 (Autoencoder Recommender) Corrected Training & Validation Curves",
                    use_container_width=True,
                )

    st.divider()

    # ------------------------------------------------------------------
    # Section B: Concept Dependency Graph Architecture
    # ------------------------------------------------------------------
    st.markdown("### Concept Dependency Graph")
    st.markdown(
        """
        The recommendation engine utilizes an authentic **Concept Co-Occurrence Dependency Graph** 
        constructed directly from multi-tagged questions in the EdNet dataset (`questions.csv`).
        """
    )

    st.markdown(
        """
        <div style="background-color: #F8FAFC; border: 1px solid #E2E8F0; border-radius: 8px; padding: 14px 18px; margin-bottom: 1.2rem;">
            <h5 style="color: #1E293B; margin-top: 0; margin-bottom: 0.5rem;">How the Graph Guides Remediation:</h5>
            <ol style="color: #475569; font-size: 0.92rem; margin-bottom: 0; padding-left: 1.2rem;">
                <li><b>Direct Mapping:</b> The engine first searches for video lectures, worked solutions, and practice questions explicitly tagged with the diagnosed weak concept.</li>
                <li><b>Prerequisite & Co-Occurrence Traversal:</b> When all direct candidate resources are exhausted or have already been attempted by the student, the recommender traverses the graph edges to identify correlated concepts tested in the same question bundles.</li>
                <li><b>Foundational Expansion:</b> Foundational learning materials from these co-occurring concepts are retrieved and prioritized by pedagogical order (lectures first).</li>
            </ol>
        </div>
        """,
        unsafe_allow_html=True,
    )

    # Live Graph Statistics from Engine
    concept_graph = {}
    if engine is not None and hasattr(engine, "recommender") and hasattr(engine.recommender, "concept_graph"):
        concept_graph = engine.recommender.concept_graph

    col_g1, col_g2, col_g3 = st.columns(3)
    with col_g1:
        st.metric(
            label="Curriculum Concept Nodes",
            value=len(concept_graph) if concept_graph else 188,
            help="Total distinct TOEIC linguistic concept tags mapped in the curriculum graph",
        )
    with col_g2:
        total_edges = sum(len(v) for v in concept_graph.values()) if concept_graph else 1896
        st.metric(
            label="Co-Occurrence Relations",
            value=f"{total_edges:,}",
            help="Directed co-occurrence edges extracted from multi-tagged EdNet question bundles",
        )
    with col_g3:
        avg_deg = (total_edges / len(concept_graph)) if concept_graph else 10.1
        st.metric(
            label="Avg Connected Concepts / Node",
            value=f"{avg_deg:.1f}",
            help="Average degree of concept interdependence across the grammar catalog",
        )

    # Interactive Sub-Graph Visualization for Current Student
    if gap_concept_ids and concept_graph:
        st.markdown("#### Live Concept Subgraph for Current Diagnosed Weaknesses")
        st.caption(
            "Visualizing the topological co-occurrence neighborhood for the student's top learning gaps. "
            "Red nodes represent diagnosed deficiencies; blue nodes represent prerequisite / correlated concepts."
        )

        subgraph_fig = _build_concept_subgraph_figure(gap_concept_ids, concept_graph)
        if subgraph_fig:
            st.plotly_chart(subgraph_fig, use_container_width=True)

        # Show table of neighbors for top gaps
        with st.expander("View Graph Neighborhood Table"):
            nbr_rows = []
            for cid in gap_concept_ids[:5]:
                neighbors = sorted(list(concept_graph.get(cid, set())))
                nbr_rows.append({
                    "Weak Concept ID": cid,
                    "Total Connected Concepts": len(neighbors),
                    "Co-Occurring Concept IDs": ", ".join(str(n) for n in neighbors[:12]) + ("..." if len(neighbors) > 12 else ""),
                })
            st.dataframe(pd.DataFrame(nbr_rows), use_container_width=True, hide_index=True)
